name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  mix-format:
    name: Mix Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Initial setup
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.9.1'
        otp-version: '22.1.1'

    - name: Install dependencies
      run: mix deps.get

    - name: Run format check
      run: mix format --check-formatted

